name: Release to Maven Central

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set version
        run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          mkdir -p $HOME/.m2
          cat > $HOME/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${MAVEN_USERNAME}</username>
                <password>${MAVEN_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF
          mvn deploy -DskipTests --settings $HOME/.m2/settings.xml -e
